### PR TITLE
Added a Machine Learning (Neural Networks)  Resource to learn

### PR DESCRIPTION
**Pull request by shazm12**
Hi @closebracket so I have added a curated course that is great for students who want to learn Machine Learning specifically Deep Learning, Recurrent Learning, and Reinforcement Learning. It has a great instructor who not only teaches various concepts and theoretical aspects of the course but also helps in building projects and teaches more additional valuable information when it comes to building Machine Learning projects. I personally learned from it and helped me to build my own project for my University Course Work. It also contains additional learning resources like Google Colab Notebooks and such.

I hope I meet all the needs for issue #44.

Thank you!!

### CODE REVIEW

**Review by closebracket — CHANGES_REQUESTED** [review]
Hi @shazm12,

Thank you for your contirbution. Please refer to the hacktoberfest rules in respect of minimum resource contributions. Once you have met the minimum requirements, I will review this again. 

Many thanks.

**Comment by sbrl** [comment]
For learning Tensorflow, I recommend the official learning hub for that: https://www.tensorflow.org/learn

.....but for undergraduate students, I recommend [Brain.js](https://www.npmjs.com/package/brain.js) instead, as it's much easier to use.

**Comment by closebracket** [comment]
@shazm12 Are you still working on this?

**Comment by shazm12** [comment]
yes by today itself it will be done @closebracket

**Comment by sbrl** [comment]
@closebracket Closing issues and PRs is fine, but I recommend never closing without an explanation as to why you've closed it to avoid confusion and frustration.

**Pull request closed without merging**
